
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author falexgl
 */
public class App extends javax.swing.JFrame {

    private ExtensionMan em;
    private boolean esSustituir; //Para modificar el comportamiento del jDialogConfirmarSustituir, depende de si sustituye o añade extensión.
    private Dimension dim;
    private static Logger logger;
    private EventosLog eventosLog;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        
        em = new ExtensionMan();
        eventosLog = em.getEventosLog();
        logger = em.getLogger();
        
        esSustituir = false;
        dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 3 - this.getSize().height / 2);
        eventosLog.registrarEvento(logger, EventosEnum.APERTURA_APP, "");
        JOptionPane.showMessageDialog(rootPane, "Advertencias:\n"
                + " -Se recomienda encarecidamente no manipular manualmente los archivos de la carpeta durante la ejecución del programa.\n"
                + " -La aplicación genera la carpeta \"extensionManagerLog\" con un archivo que recopila los posibles errores.\n"
                + " -Para un correcto funcionamiento, no modificar el nombre del ejecutable \"ExtensionManagerGUI\".");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMenuPpal = new javax.swing.ButtonGroup();
        jDialogMostrarContenido = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelContenidoCarpeta = new javax.swing.JLabel();
        jButtonVolverListarContenido = new javax.swing.JButton();
        jDialogSustituir = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNuevaExtensionSustituir = new javax.swing.JTextField();
        jButtonAceptarSustituir = new javax.swing.JButton();
        jButtonCancelarSustituir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonConservar = new javax.swing.JRadioButton();
        jRadioButtonEliminar = new javax.swing.JRadioButton();
        jDialogConfirmarSustituir = new javax.swing.JDialog();
        jLabelConfirmarSustituir = new javax.swing.JLabel();
        jButtonOkConfirmarSustituir = new javax.swing.JButton();
        jButtonCancelarConfirmarSustituir = new javax.swing.JButton();
        buttonGroupSustituirExtension = new javax.swing.ButtonGroup();
        jDialogAnadirExtension = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabelAnadirExtension = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAnadirExtension = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonConservar1 = new javax.swing.JRadioButton();
        jRadioButtonEliminar1 = new javax.swing.JRadioButton();
        jButtonAceptarAnadir = new javax.swing.JButton();
        jButtonCancelarAnadir = new javax.swing.JButton();
        buttonGroupAnadirExtension = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonListar = new javax.swing.JRadioButton();
        jRadioButtonSustituir = new javax.swing.JRadioButton();
        jRadioButtonAnadir = new javax.swing.JRadioButton();
        jButtonOkMain = new javax.swing.JButton();

        jLabelContenidoCarpeta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelContenidoCarpeta.setText("dfsf");
        jLabelContenidoCarpeta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(jLabelContenidoCarpeta);

        jButtonVolverListarContenido.setText("Volver");
        jButtonVolverListarContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverListarContenidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogMostrarContenidoLayout = new javax.swing.GroupLayout(jDialogMostrarContenido.getContentPane());
        jDialogMostrarContenido.getContentPane().setLayout(jDialogMostrarContenidoLayout);
        jDialogMostrarContenidoLayout.setHorizontalGroup(
            jDialogMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jDialogMostrarContenidoLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jButtonVolverListarContenido)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jDialogMostrarContenidoLayout.setVerticalGroup(
            jDialogMostrarContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMostrarContenidoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVolverListarContenido)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("SUSTITUIR EXTENSIÓN");

        jLabel3.setText("Seleccione la extensión que quiere sustituir:");

        jLabel4.setText("Introduzca la nueva extensión (no incluya punto):");

        jButtonAceptarSustituir.setText("Aceptar");
        jButtonAceptarSustituir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarSustituirActionPerformed(evt);
            }
        });

        jButtonCancelarSustituir.setText("Cancelar");
        jButtonCancelarSustituir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarSustituirActionPerformed(evt);
            }
        });

        jLabel5.setText("¿Desea conservar los archivos originales?");

        buttonGroupSustituirExtension.add(jRadioButtonConservar);
        jRadioButtonConservar.setSelected(true);
        jRadioButtonConservar.setText("Sí");

        buttonGroupSustituirExtension.add(jRadioButtonEliminar);
        jRadioButtonEliminar.setText("No");

        javax.swing.GroupLayout jDialogSustituirLayout = new javax.swing.GroupLayout(jDialogSustituir.getContentPane());
        jDialogSustituir.getContentPane().setLayout(jDialogSustituirLayout);
        jDialogSustituirLayout.setHorizontalGroup(
            jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSustituirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSustituirLayout.createSequentialGroup()
                        .addComponent(jRadioButtonConservar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEliminar)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNuevaExtensionSustituir))
                .addGap(25, 25, 25))
            .addGroup(jDialogSustituirLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButtonAceptarSustituir)
                .addGap(57, 57, 57)
                .addComponent(jButtonCancelarSustituir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogSustituirLayout.setVerticalGroup(
            jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSustituirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNuevaExtensionSustituir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonConservar)
                    .addComponent(jRadioButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jDialogSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptarSustituir)
                    .addComponent(jButtonCancelarSustituir))
                .addGap(14, 14, 14))
        );

        jLabelConfirmarSustituir.setText("jLabel5");
        jLabelConfirmarSustituir.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonOkConfirmarSustituir.setText("Confirmar");
        jButtonOkConfirmarSustituir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkConfirmarSustituirActionPerformed(evt);
            }
        });

        jButtonCancelarConfirmarSustituir.setText("Cancelar");
        jButtonCancelarConfirmarSustituir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarConfirmarSustituirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogConfirmarSustituirLayout = new javax.swing.GroupLayout(jDialogConfirmarSustituir.getContentPane());
        jDialogConfirmarSustituir.getContentPane().setLayout(jDialogConfirmarSustituirLayout);
        jDialogConfirmarSustituirLayout.setHorizontalGroup(
            jDialogConfirmarSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelConfirmarSustituir, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogConfirmarSustituirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOkConfirmarSustituir)
                .addGap(26, 26, 26)
                .addComponent(jButtonCancelarConfirmarSustituir)
                .addGap(14, 14, 14))
        );
        jDialogConfirmarSustituirLayout.setVerticalGroup(
            jDialogConfirmarSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConfirmarSustituirLayout.createSequentialGroup()
                .addComponent(jLabelConfirmarSustituir, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogConfirmarSustituirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOkConfirmarSustituir)
                    .addComponent(jButtonCancelarConfirmarSustituir))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("AÑADIR EXTENSIÓN");

        jLabelAnadirExtension.setText("jLabel7");

        jLabel7.setText("Introduzca la nueva extensión (no incluya punto):");

        jLabel8.setText("¿Desea conservar los archivos originales?");

        buttonGroupAnadirExtension.add(jRadioButtonConservar1);
        jRadioButtonConservar1.setSelected(true);
        jRadioButtonConservar1.setText("Sí");

        buttonGroupAnadirExtension.add(jRadioButtonEliminar1);
        jRadioButtonEliminar1.setText("No");

        jButtonAceptarAnadir.setText("Aceptar");
        jButtonAceptarAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarAnadirActionPerformed(evt);
            }
        });

        jButtonCancelarAnadir.setText("Cancelar");
        jButtonCancelarAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAnadirExtensionLayout = new javax.swing.GroupLayout(jDialogAnadirExtension.getContentPane());
        jDialogAnadirExtension.getContentPane().setLayout(jDialogAnadirExtensionLayout);
        jDialogAnadirExtensionLayout.setHorizontalGroup(
            jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                .addGroup(jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel6))
                            .addComponent(jLabelAnadirExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonConservar1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonEliminar1))
                                    .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAnadirExtension))))))
                    .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButtonAceptarAnadir)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonCancelarAnadir)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDialogAnadirExtensionLayout.setVerticalGroup(
            jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAnadirExtensionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAnadirExtension)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAnadirExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButtonConservar1)
                    .addComponent(jRadioButtonEliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAnadirExtensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptarAnadir)
                    .addComponent(jButtonCancelarAnadir))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("EXTENSION MANAGER");

        buttonGroupMenuPpal.add(jRadioButtonListar);
        jRadioButtonListar.setText("Listar archivos");

        buttonGroupMenuPpal.add(jRadioButtonSustituir);
        jRadioButtonSustituir.setText("Sustituir archivos");

        buttonGroupMenuPpal.add(jRadioButtonAnadir);
        jRadioButtonAnadir.setText("Añadir extensión");

        jButtonOkMain.setText("OK");
        jButtonOkMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSustituir)
                            .addComponent(jRadioButtonListar)
                            .addComponent(jRadioButtonAnadir)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButtonOkMain))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSustituir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonAnadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOkMain)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkMainActionPerformed
        if (jRadioButtonListar.isSelected()) {
            jLabelContenidoCarpeta.setText(em.mostrarContenido());
            jDialogMostrarContenido.setSize(500, 350);
            jDialogMostrarContenido.setLocationRelativeTo(this);
            jDialogMostrarContenido.show();
            jDialogMostrarContenido.setVisible(true);
        } else if (jRadioButtonSustituir.isSelected()) {
            jComboBox1.removeAllItems();
            HashMap<String, ArrayList<String>> agrupacionExtensiones = em.getAgrupacionExtensiones();
            for (Map.Entry<String, ArrayList<String>> entry : agrupacionExtensiones.entrySet()) {
                if (!entry.getKey().equals("")) {
                    jComboBox1.addItem(entry.getKey());
                }
            }
            jDialogSustituir.setSize(400, 250);
            jDialogSustituir.setLocationRelativeTo(this);
            jDialogSustituir.setVisible(true);
        } else if (jRadioButtonAnadir.isSelected()) {
            HashMap<String, ArrayList<String>> agrupacionExtensiones = em.getAgrupacionExtensiones();
            if (!agrupacionExtensiones.containsKey("")) {
                JOptionPane.showMessageDialog(rootPane, "No hay archivos sin extensión en la ubicación actual.");
            } else {
                jLabelAnadirExtension.setText("<html>Se va a añadir extensión a <strong>" + agrupacionExtensiones.get("").size() + " archivo/s</strong>.</html>");
                jDialogAnadirExtension.setSize(440, 225);
                jDialogAnadirExtension.setLocationRelativeTo(this);
                jDialogAnadirExtension.setVisible(true);
            } 

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecciona alguna opción para poder continuar.");
        }

    }//GEN-LAST:event_jButtonOkMainActionPerformed

    private void jButtonVolverListarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverListarContenidoActionPerformed
        jDialogMostrarContenido.dispose();
    }//GEN-LAST:event_jButtonVolverListarContenidoActionPerformed

    private void jButtonCancelarSustituirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarSustituirActionPerformed
        jDialogSustituir.dispose();
    }//GEN-LAST:event_jButtonCancelarSustituirActionPerformed

    private void jButtonAceptarSustituirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarSustituirActionPerformed
        if(jTextFieldNuevaExtensionSustituir.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Al no indicar una nueva extensión, se eliminará la extensión oritinal dejando a los archivos sin extensión.");
        }
        String texto = "<html><p><strong>Configuración seleccionada:</strong></p>"
                + "<ul><li>Extensión original: <strong>." + jComboBox1.getSelectedItem().toString() + "</strong></li>";
        texto += (jTextFieldNuevaExtensionSustituir.getText().equals(""))
                ? "<li><strong>Se eliminará la extensión de los archivos con la extensión original indicada.</strong></li>"
                : "<li>Nueva extensión: <strong>." + jTextFieldNuevaExtensionSustituir.getText() + "</strong></li>";
        texto += (jRadioButtonConservar.isSelected())
                ? "<li>Se <strong>conservarán</strong> los archivos originales.</li></ul>"
                : "<li>Se <strong>eliminarán</strong> los archivos originales.</li></ul>";
        texto += "<p>¿Desea continuar?</p></html>";

        esSustituir = true;

        jLabelConfirmarSustituir.setText(texto);
        jDialogConfirmarSustituir.setSize(330, 210);
        jDialogConfirmarSustituir.setLocationRelativeTo(this);
        jDialogConfirmarSustituir.setVisible(true);
    }//GEN-LAST:event_jButtonAceptarSustituirActionPerformed

    private void jButtonCancelarConfirmarSustituirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarConfirmarSustituirActionPerformed
        jDialogConfirmarSustituir.dispose();
    }//GEN-LAST:event_jButtonCancelarConfirmarSustituirActionPerformed

    private void jButtonOkConfirmarSustituirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkConfirmarSustituirActionPerformed
        if (esSustituir) {
            boolean mantenerOriginal = (jRadioButtonConservar.isSelected()) ? true : false;
            em.modificarExtension(jComboBox1.getSelectedItem().toString(), jTextFieldNuevaExtensionSustituir.getText(), mantenerOriginal);
            JOptionPane.showMessageDialog(rootPane, "Se han modificado " + em.getArchivosModificados() + " archivos.");
            jDialogConfirmarSustituir.dispose();
            jDialogSustituir.dispose();
        } else {
            boolean mantenerOriginal = (jRadioButtonConservar1.isSelected()) ? true : false;
            em.modificarExtension("", jTextFieldAnadirExtension.getText(), mantenerOriginal);
            JOptionPane.showMessageDialog(rootPane, "Se ha añadido extensión a " + em.getArchivosModificados() + " archivos.");
            jDialogConfirmarSustituir.dispose();
            jDialogAnadirExtension.dispose();
        }
    }//GEN-LAST:event_jButtonOkConfirmarSustituirActionPerformed

    private void jButtonAceptarAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarAnadirActionPerformed
        if (jTextFieldAnadirExtension.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar la extensión que quiera añadir.");
        } else {
            String texto = "<html><p><strong>Configuración seleccionada:</strong></p>"
                    + "<ul><li>Se añadirá la siguiente extensión: .<strong>" + jTextFieldAnadirExtension.getText() + "</strong></li>";
            texto += (jRadioButtonConservar1.isSelected())
                    ? "<li>Se <strong>conservarán</strong> los archivos originales.</li></ul>"
                    : "<li>Se <strong>eliminarán</strong> los archivos originales.</li></ul>";
            texto += "<p>¿Desea continuar?</p></html>";

            esSustituir = false;
            
            jLabelConfirmarSustituir.setText(texto);
            jDialogConfirmarSustituir.setSize(330, 180);
            jDialogConfirmarSustituir.setLocationRelativeTo(this);
            jDialogConfirmarSustituir.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAceptarAnadirActionPerformed

    private void jButtonCancelarAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAnadirActionPerformed
        jDialogAnadirExtension.dispose();
    }//GEN-LAST:event_jButtonCancelarAnadirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        eventosLog.registrarEvento(logger, EventosEnum.CIERRE_APP, "");
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAnadirExtension;
    private javax.swing.ButtonGroup buttonGroupMenuPpal;
    private javax.swing.ButtonGroup buttonGroupSustituirExtension;
    private javax.swing.JButton jButtonAceptarAnadir;
    private javax.swing.JButton jButtonAceptarSustituir;
    private javax.swing.JButton jButtonCancelarAnadir;
    private javax.swing.JButton jButtonCancelarConfirmarSustituir;
    private javax.swing.JButton jButtonCancelarSustituir;
    private javax.swing.JButton jButtonOkConfirmarSustituir;
    private javax.swing.JButton jButtonOkMain;
    private javax.swing.JButton jButtonVolverListarContenido;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialogAnadirExtension;
    private javax.swing.JDialog jDialogConfirmarSustituir;
    private javax.swing.JDialog jDialogMostrarContenido;
    private javax.swing.JDialog jDialogSustituir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAnadirExtension;
    private javax.swing.JLabel jLabelConfirmarSustituir;
    private javax.swing.JLabel jLabelContenidoCarpeta;
    private javax.swing.JRadioButton jRadioButtonAnadir;
    private javax.swing.JRadioButton jRadioButtonConservar;
    private javax.swing.JRadioButton jRadioButtonConservar1;
    private javax.swing.JRadioButton jRadioButtonEliminar;
    private javax.swing.JRadioButton jRadioButtonEliminar1;
    private javax.swing.JRadioButton jRadioButtonListar;
    private javax.swing.JRadioButton jRadioButtonSustituir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAnadirExtension;
    private javax.swing.JTextField jTextFieldNuevaExtensionSustituir;
    // End of variables declaration//GEN-END:variables
}
